### PR TITLE
added name 

### PR DESCRIPTION
**Pull request by stakrift**

### CODE REVIEW

**Review by Vivek09Chahal — APPROVED** [review]

**Comment by stakrift** [comment]
@Vivek09Chahal @kanakOS01 heyy im not getting the option for merging pull requests- Any solution

**Comment by Vivek09Chahal** [comment]
> @Vivek09Chahal @kanakOS01 heyy im not getting the option for merging pull requests- Any solution

Vansh, you are talking about creating pull request. Am I right ?

**Comment by Vivek09Chahal** [comment]
> @Vivek09Chahal @kanakOS01 heyy im not getting the option for merging pull requests- Any solution

Vansh, you are talking about creating pull request. Am I right?

**Comment by stakrift** [comment]
@Vivek09Chahal i already created the pull rqst but the changes i made in fork repo isnt visible in original one maybe its coz i dont have the write access otherwise there will be an option of merge pull request 
below is an example 
Screenshot 2024-03-31 234352

**Comment by Vivek09Chahal** [comment]
Ya you cannot merge into the main branch yourself, it will only be able to merge by the one whose repository it is. So, yea if kanak has proven your request you will see the changes in the main branch as well.

**Comment by stakrift** [comment]
Ohh got it

**Pull request merged**
